apiVersion: v1
kind: Service
metadata:
  name: footcap-service
spec:
  type: NodePort
  selector:
    app: footcap
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # access via EC2-PUBLIC-IP:30080
